### PR TITLE
Use Boost test framework

### PR DESCRIPTION
**Pull request by jakirkham**
This replaces the VIGRA test framework that is used currently with the Boost test framework.

### CODE REVIEW

**Comment by jakirkham** [comment]
This works and tests out. The print function doesn't seem to always be used as it should; however, the copy provided here has been tested and found to work. It should be moved into VIGRA somehow. See this issue ( https://github.com/ukoethe/vigra/issues/276 ).

**Comment by ukoethe** [comment]
Just out of curiosity: I suppose that this move fixes certain limitations of the VIGRA test framework. Can you elaborate a bit? Thanks.

**Comment by jakirkham** [comment]
So, I didn't switch because of any dislike of VIGRA's testing framework or really any like of Boost's. Actually, I tried switching the Python bindings from VIGRA/Boost to Cython for a variety of reasons. Once I began making the switch, it no longer made sense to me to keep VIGRA around as a required dependency simply for testing. As Boost is already a required dependency, it made sense to try to use their testing framework if possible so that's what I did.

**Comment by ukoethe** [comment]
> I tried switching the Python bindings from VIGRA/Boost to Cython for a variety of reasons.

Interesting. How would you compare the experience between boost::python and cython?

**Comment by jakirkham** [comment]
It's amazing. One of the biggest advantages is it allows one to span the range of having full Python features to extremely optimized C-level speed in a still very Python-like language. This plays out in a variety of ways. Here are few:

* Exceptions in Cython come through and can be handled by Python with no extra effort.
* Casting between Python and basic C types requires little effort.
* Profiling with existing python tools like `line_profiler` can be added easily.
* Use of fused types in Cython makes it possible to reduce the number of bindings written.
* Use of C++ style templates in Cython makes it easier to bind C++ code.
* Optional typing. (allows speed up when desired, but doesn't require typing something that may be better off not typed)
* Trivial release or acquisition of the GIL using `with` syntax (not that RAII-style C++ acquisition is bad; this just doesn't even require an object to be associated making it easy to nest sections of this sort).
* Use of memory views with constraints (C-order/F-order) makes it easy to bind arrays of any sort.
* Decorator and/or comment style optimizations for increasing speed. (turning off bound checking, etc.)
* Support for C++ STL objects (excepting C++11 objects; looks like this will change in the future) and all C functions.
* Code written is shorter. (cut lines written by more than half)

**Pull request merged**
